// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcJLTtguijkX5suPXJ_aRWCeqx0Zh_bJk',
    appId: '1:343798821292:web:135ea4d69c1d6a9b884a09',
    messagingSenderId: '343798821292',
    projectId: 'calendar-2c84c',
    authDomain: 'calendar-2c84c.firebaseapp.com',
    storageBucket: 'calendar-2c84c.firebasestorage.app',
    measurementId: 'G-KQH6KXE3BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GHLLt_D4IRVZTl2yo8mwor4chPTG9H0',
    appId: '1:343798821292:android:a64657057164fd9c884a09',
    messagingSenderId: '343798821292',
    projectId: 'calendar-2c84c',
    storageBucket: 'calendar-2c84c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_9uo3cdu76OISf6jGaWKdPvH8oq7dnuo',
    appId: '1:343798821292:ios:6bd95e78964a658a884a09',
    messagingSenderId: '343798821292',
    projectId: 'calendar-2c84c',
    storageBucket: 'calendar-2c84c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_9uo3cdu76OISf6jGaWKdPvH8oq7dnuo',
    appId: '1:343798821292:ios:6bd95e78964a658a884a09',
    messagingSenderId: '343798821292',
    projectId: 'calendar-2c84c',
    storageBucket: 'calendar-2c84c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcJLTtguijkX5suPXJ_aRWCeqx0Zh_bJk',
    appId: '1:343798821292:web:e1a670f525327039884a09',
    messagingSenderId: '343798821292',
    projectId: 'calendar-2c84c',
    authDomain: 'calendar-2c84c.firebaseapp.com',
    storageBucket: 'calendar-2c84c.firebasestorage.app',
    measurementId: 'G-YW8VF44JHN',
  );
}
